added a NonBinary Option to "PatientSex"
FNNDSC/ChRIS_ultron_backEnd pull request #440
Opened 2022-10-11 13:09 UTC by cornelia247

Updated the Patient sex to include Nonbinary option

2022-10-12 03:19 UTC, jennydaman commented
Continuing from https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/438#issuecomment-1274886168, do you want to remove the `choices` kwarg altogether?

2022-10-12 07:41 UTC, cornelia247 commented
No I feel like that would be very confusing. Adding an "other" choice should round it up nice with the three we have now. What do you think?

2022-10-14 07:30 UTC, jennydaman commented
@cornelia247 huge apology from me! I should have just looked it up... According to the DICOM standard, "M", "F", and "O" are the only three valid values for "PatientSex." Would you revert 9bd8d3440adf050a0df1770cefbf8c0c1f470d24? After doing so, I'll be happy to merge it.

2022-10-14 08:32 UTC, jennydaman requested changes

2022-10-14 08:32 UTC, jennydaman commented on chris_backend/feeds/views.py
> +        if not isinstance(self.request.data, dict) or not getattr(self.request.data, '_mutable', 1):
Why did you merge ea06f75dcb3310cd7915d609a06a2fb2698235a0?

I think you should simply do a

```shell
git reset --hard 14f5281a46f79db29b0769b2279f36ea5e770f06
git push --force
```

2022-10-14 08:57 UTC, closed without merging