Unauthenticated user acess to /api/v1/plugins and /api/v1/pipelines APIs
FNNDSC/ChRIS_ultron_backEnd pull request #456
Opened 2022-10-25 11:38 UTC by afrinthegoldfish

## Made Global API available to anonymous users
Previously ChRIS_ultron_backend used to serve api to authenticated and authorized users only. But Global API /api/v1/plugins and /api/v1/pipelines can be exposed to unauthenticated users as read only. This code changes should resolve this issue #452

2022-10-26 14:52 UTC, afrinthegoldfish commented
@jennydaman please review

2022-11-04 05:56 UTC, jennydaman requested changes

2022-11-04 05:56 UTC, jennydaman commented on chris_backend/pipelines/tests/test_views.py
> -        self.assertEqual(response.status_code, status.HTTP_401_UNAUTHORIZED)
instead of deleting this line, maybe we can instead assert that the status is 200 OK?

2022-11-04 05:56 UTC, jennydaman commented on chris_backend/pipelines/models.py
> +        if user.username == 'chris' or not user.is_authenticated:
Here, we have a special case where the "chris" user is able to see all pipelines.

This is not what we want if the user is not authenticated. Instead, we should change the lookup on line 87 such that for anonymous user, return all pipelines where `locked=False`.

2022-11-04 05:56 UTC, jennydaman commented on chris_backend/pipelines/models.py
> +        if user.username == 'chris' or not user.is_authenticated:
Explanation: `locked` is a poorly named attribute, think of it as meaning whether or not a pipeline is private.

2023-01-24 22:35 UTC, jennydaman commented
succeeded by https://github.com/FNNDSC/ChRIS_ultron_backEnd/pull/477

2023-01-24 22:35 UTC, closed without merging